export const genreList = [
	'Action & Adventures',
	'Art & Crafts',
	'Biographies & Memoirs',
	'Business & Economics',
	'Children & Young Adult',
	'Comics & Mangas',
	'Crime & Mystery',
	'Fantasy',
	'Fiction & Literature',
	'Health & Personal Development',
	'History',
	'Home & Lifestyle',
	'Horror & Thriller',
	'Humor',
	'Law & Politics',
	'Romance',
	'Society & Social Sciences',
	'Sports',
	'Technology & Medicine',
	'Travel',
]
