const readerStyles = {
	arrow: {
		display: 'none',
	},
	readerArea: {
		position: 'relative',
		zIndex: 1,
		height: '100%',
		width: '100%',
		backgroundColor: '#030b17',
		transition: 'all .3s ease',
	},
	titleArea: {
		position: 'absolute',
		top: 16,
		left: 50,
		right: 50,
		textAlign: 'center',
		color: '#999',
	},
	reader: {
		position: 'absolute',
		top: 20,
		left: 20,
		bottom: 30,
		right: 20,
	},
	arrow: {
		outline: 'none',
		border: 'none',
		background: 'none',
		position: 'absolute',
		top: '50%',
		marginTop: -32,
		fontSize: 16,
		padding: '0 4px',
		color: '#c084fc',
		fontFamily: 'arial, sans-serif',
		cursor: 'pointer',
		userSelect: 'none',
		appearance: 'none',
		fontWeight: 'normal',
	},
	arrowHover: {
		color: '#a855f7',
	},
	tocBackground: {
		position: 'absolute',
		left: 256,
		top: 0,
		bottom: 0,
		right: 0,
		zIndex: 1,
	},
	tocArea: {
		position: 'absolute',
		left: 0,
		top: 0,
		bottom: 0,
		zIndex: 0,
		width: 256,
		overflowY: 'auto',
		WebkitOverflowScrolling: 'touch',
		background: '#8C6AFF',
		padding: '10px 0',
	},
	tocAreaButton: {
		userSelect: 'none',
		appearance: 'none',
		background: 'none',
		border: 'none',
		display: 'block',
		fontFamily: 'sans-serif',
		width: '100%',
		fontSize: '.9em',
		textAlign: 'left',
		padding: '.9em 1em',
		borderBottom: '1px solid #ddd',
		color: '#192132',
		boxSizing: 'border-box',
		outline: 'none',
		cursor: 'pointer',
	},
	tocButton: {
		background: 'none',
		border: 'none',
		width: 32,
		height: 32,
		position: 'absolute',
		top: 10,
		left: 10,
		borderRadius: 2,
		outline: 'none',
		cursor: 'pointer',
	},
	tocButtonExpanded: {
		background: '#8C6AFF',
	},
	tocButtonBar: {
		position: 'absolute',
		width: '60%',
		background: '#c084fc',
		height: 2,
		left: '50%',
		margin: '-1px -30%',
		top: '50%',
		transition: 'all .5s ease',
	},
	loadingView: {
		position: 'absolute',
		top: '50%',
		left: '10%',
		right: '10%',
		color: 'black',
		fontSize: '1.5rem',
		textAlign: 'center',
		margintop: '-.5em',
	},
}

export default readerStyles
