const readerStyles = {
	readerArea: {
		position: 'relative',
		zIndex: 1,
		height: '100%',
		width: '100%',
		backgroundColor: '#0D1117',
		transition: 'all .3s ease',
	},
	titleArea: {
		position: 'absolute',
		top: 16,
		left: 50,
		right: 50,
		textAlign: 'center',
		color: '#999',
	},
	reader: {
		position: 'absolute',
		top: 0,
		left: 0,
		bottom: 30,
		right: 0,
	},
	arrow: {
		display: 'none',
		// outline: 'none',
		// border: 'none',
		// background: 'none',
		// position: 'absolute',
		// top: '50%',
		// marginTop: -32,
		// fontSize: 16,
		// padding: '0 4px',
		// color: '#c084fc',
		// fontFamily: 'arial, sans-serif',
		// cursor: 'pointer',
		// userSelect: 'none',
		// appearance: 'none',
		// fontWeight: 'normal',
	},
	arrowHover: {
		// color: '#a855f7',
	},
	tocBackground: {
		position: 'absolute',
		left: 256,
		top: 0,
		bottom: 0,
		right: 0,
		zIndex: 1,
	},
	tocArea: {
		position: 'absolute',
		left: 0,
		top: 0,
		bottom: 0,
		zIndex: 0,
		width: 256,
		overflowY: 'auto',
		WebkitOverflowScrolling: 'touch',
		background: '#0C111B',
		padding: '10px 0',
	},
	tocAreaButton: {
		userSelect: 'none',
		appearance: 'none',
		background: 'none',
		border: 'none',
		display: 'block',
		fontFamily: 'sans-serif',
		width: '100%',
		fontSize: '.9em',
		textAlign: 'left',
		padding: '.9em 1em',
		borderBottom: '1px solid #6b21a8', //8C6AFF,
		color: '#8C6AFF',
		boxSizing: 'border-box',
		outline: 'none',
		cursor: 'pointer',
	},
	tocButton: {
		background: 'none',
		border: 'none',
		width: 32,
		height: 32,
		position: 'absolute',
		top: 1.5,
		left: 1.5,
		borderRadius: 2,
		marginRight: 2,
		zIndex: 10,
		outline: 'none',
		cursor: 'pointer',
	},
	tocButtonExpanded: {
		background: '#8C6AFF',
	},
	loadingView: {
		position: 'absolute',
		top: '50%',
		left: '10%',
		right: '10%',
		fontSize: '2rem',
		textAlign: 'center',
		margintop: '-.5em',
		color: '#8C6AFF',
	},
}

export default readerStyles
